### ISSUE TITLE
Discrepancy when using the stack template?

### ISSUE THREAD

**Issue by namin** [lsrcz/grisette#298]
Hi,

I am enjoying exploring Grisette!

I tried creating a stack project using the template like suggested in the README, but when I copy the https://github.com/lsrcz/grisette/blob/main/examples/basic/Main.hs to replace the Main, I get that `makeGrisetteBasicADT` is not in scope even though Grisette is imported, when running the app.

I confirm that running the app in the examples directory in this repo works, however.

Does the template need to be updated?

Thanks. Best wishes, ~n

**Comment by lsrcz** [comment]
Hi Nada,

Thanks for your interest in Grisette! It is not the template issue---it is tracking the latest release version instead of the GitHub version.

This `makeGrisetteBasicADT` has been recently added and isn't in the Hackage version. You may consider changing the stack.yaml generated from the template from

```yaml
extra-deps:
- grisette-0.12.0.0
```
to
```yaml
extra-deps:
- git: https://github.com/lsrcz/grisette.git
  commit: aa4556d99a0e73c43d0b1a0fd530928d7a55cb81
```
to use the current head version on GitHub.

Hope this helps!
